FROM node:20-alpine
WORKDIR /app
RUN addgroup -g 1001 -S nodejs && adduser -S nestjs -u 1001
COPY package*.json ./
RUN npm install
RUN chown -R nestjs:nodejs node_modules package*.json
USER nestjs
EXPOSE 4002
CMD ["npm", "run", "start:dev"]
